cmake_minimum_required(VERSION 3.24)

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(work "${TEST_ROOT}/runtime-${run_id}")
set(manifest "${work}/manifest.cmake")
file(MAKE_DIRECTORY "${work}/source" "${work}/runtime")
file(WRITE "${work}/source/font.txt" "original font")
file(WRITE "${work}/source/shader.bin" "original shader")
file(WRITE "${work}/runtime/user.txt" "keep user data")

function(write_manifest sources names)
    file(WRITE "${manifest}"
"set(stage_root [==[${work}/runtime]==])
set(stage_state [==[${work}/state.txt]==])
set(stage_sources [==[${sources}]==])
set(stage_names [==[${names}]==])
")
endfunction()

function(stage expect_success)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DMANIFEST=${manifest}" -P "${STAGING_SCRIPT}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expect_success AND NOT result STREQUAL "0")
        message(FATAL_ERROR "Staging failed: ${output}${error}")
    elseif(NOT expect_success AND result STREQUAL "0")
        message(FATAL_ERROR "Invalid staging request unexpectedly succeeded")
    endif()
endfunction()

function(expect_contents path expected)
    file(READ "${path}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Unexpected contents of ${path}: ${actual}")
    endif()
endfunction()

write_manifest("${work}/source/font.txt;${work}/source/shader.bin"
    "fonts/test font.txt;shaders/test.bin")
stage(TRUE)
expect_contents("${work}/runtime/fonts/test font.txt" "original font")
expect_contents("${work}/runtime/shaders/test.bin" "original shader")
file(TIMESTAMP "${work}/runtime/fonts/test font.txt" before_copy "%s.%f")
file(TIMESTAMP "${work}/state.txt" before_state "%s.%f")
stage(TRUE)
file(TIMESTAMP "${work}/runtime/fonts/test font.txt" after_copy "%s.%f")
file(TIMESTAMP "${work}/state.txt" after_state "%s.%f")
if(NOT before_copy STREQUAL after_copy OR NOT before_state STREQUAL after_state)
    message(FATAL_ERROR "An unchanged staging run rewrote its outputs")
endif()

file(WRITE "${work}/source/font.txt" "changed font")
stage(TRUE)
expect_contents("${work}/runtime/fonts/test font.txt" "changed font")
file(REMOVE "${work}/runtime/shaders/test.bin")
stage(TRUE)
expect_contents("${work}/runtime/shaders/test.bin" "original shader")

# Rename/remove managed files without removing unrelated runtime files.
write_manifest("${work}/source/font.txt" "fonts/renamed.txt")
stage(TRUE)
expect_contents("${work}/runtime/fonts/renamed.txt" "changed font")
if(EXISTS "${work}/runtime/fonts/test font.txt" OR EXISTS "${work}/runtime/shaders/test.bin")
    message(FATAL_ERROR "Obsolete managed files were not removed")
endif()
expect_contents("${work}/runtime/user.txt" "keep user data")
write_manifest("" "")
stage(TRUE)
if(EXISTS "${work}/runtime/fonts/renamed.txt")
    message(FATAL_ERROR "An empty manifest did not remove its old managed file")
endif()
expect_contents("${work}/runtime/user.txt" "keep user data")

file(WRITE "${work}/sentinel.txt" "outside destination")
write_manifest("${work}/source/font.txt" "../sentinel.txt")
stage(FALSE)
expect_contents("${work}/sentinel.txt" "outside destination")
write_manifest("${work}/source/font.txt" "${work}/sentinel.txt")
stage(FALSE)
expect_contents("${work}/sentinel.txt" "outside destination")
write_manifest("${work}/source/font.txt" "first.txt;second.txt")
stage(FALSE)

# A malformed historical manifest must not delete outside the staging root.
file(WRITE "${work}/state.txt" "../sentinel.txt")
write_manifest("" "")
stage(FALSE)
expect_contents("${work}/sentinel.txt" "outside destination")
