cmake_minimum_required(VERSION 3.24)

# Exercise the actual build graph, especially missing-output detection, using
# the parent build's generator. No compiler or third-party packages are needed.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(work "${TEST_ROOT}/build-graph-${run_id}")
set(source "${work}/source")
set(binary "${work}/build")
set(runtime "${binary}/runtime/${TEST_CONFIG}/assets")
file(MAKE_DIRECTORY "${source}/assets/fonts")
file(WRITE "${source}/assets/fonts/test.txt" "font")
file(WRITE "${source}/shader.sc" "shader one")
file(WRITE "${source}/CMakeLists.txt"
"cmake_minimum_required(VERSION 3.24)
project(runtime_staging_fixture LANGUAGES NONE)
include([==[${RUNTIME_MODULE}]==])
add_custom_target(viewer)
add_custom_command(OUTPUT [==[${binary}/assets/shaders/test.bin]==]
    COMMAND \"\${CMAKE_COMMAND}\" -E make_directory [==[${binary}/assets/shaders]==]
    COMMAND \"\${CMAKE_COMMAND}\" -E copy [==[${source}/shader.sc]==] [==[${binary}/assets/shaders/test.bin]==]
    DEPENDS [==[${source}/shader.sc]==] VERBATIM)
set_property(TARGET viewer PROPERTY WOBY_SHADER_OUTPUTS [==[${binary}/assets/shaders/test.bin]==])
woby_stage_assets(viewer [==[${binary}/runtime/$<CONFIG>]==])
")
set(generator_args -G "${TEST_GENERATOR}")
if(TEST_PLATFORM)
    list(APPEND generator_args -A "${TEST_PLATFORM}")
endif()
if(NOT TEST_GENERATOR MATCHES "Visual Studio|Xcode|Multi-Config")
    list(APPEND generator_args "-DCMAKE_BUILD_TYPE=${TEST_CONFIG}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
    ${generator_args}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Fixture configure failed: ${output}${error}")
endif()

function(build_assets)
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${binary}"
        --config "${TEST_CONFIG}" --target viewer --parallel 2
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Fixture build failed: ${output}${error}")
    endif()
endfunction()

function(expect_contents path expected)
    file(READ "${path}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Unexpected contents of ${path}: ${actual}")
    endif()
endfunction()

function(expect_no_staging)
    set(stamp "${binary}/runtime-staging/viewer-assets-${TEST_CONFIG}.stamp")
    file(TIMESTAMP "${stamp}" before "%s.%f")
    build_assets()
    file(TIMESTAMP "${stamp}" after "%s.%f")
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "A no-change build repeated asset staging")
    endif()
endfunction()

build_assets()
expect_contents("${runtime}/fonts/test.txt" "font")
expect_contents("${runtime}/shaders/test.bin" "shader one")
expect_no_staging()
file(REMOVE "${runtime}/fonts/test.txt")
build_assets()
expect_contents("${runtime}/fonts/test.txt" "font")
file(WRITE "${source}/shader.sc" "shader two")
build_assets()
expect_contents("${runtime}/shaders/test.bin" "shader two")
file(WRITE "${source}/assets/added.txt" "added")
build_assets()
expect_contents("${runtime}/added.txt" "added")
file(WRITE "${source}/assets/added.txt" "edited")
build_assets()
expect_contents("${runtime}/added.txt" "edited")
file(WRITE "${runtime}/user.txt" "unmanaged")
file(REMOVE "${source}/assets/added.txt")
build_assets()
if(EXISTS "${runtime}/added.txt")
    message(FATAL_ERROR "The deleted source asset remains staged")
endif()
expect_contents("${runtime}/user.txt" "unmanaged")
expect_no_staging()
