"""Regenerate the portable surface quality samples using only Python's standard library.

Open the checked-in .woby files directly; running this script is optional.
Expected values below come from the construction, not Woby's implementation.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def write_obj(name, points, faces, description):
    text = f"# {description}\n# Coordinates in millimeters.\no surface\n"
    text += "".join("v " + " ".join(f"{v:.12g}" for v in p) + "\n" for p in points)
    text += "".join("f " + " ".join(str(i + 1) for i in face) + "\n" for face in faces)
    (ROOT / name).write_text(text, encoding="utf-8", newline="\n")


def grid(name, xs, ys, description):
    points = [(x, y, 0) for y in ys for x in xs]
    faces = []
    for y in range(len(ys) - 1):
        for x in range(len(xs) - 1):
            i = y * len(xs) + x
            faces.extend([(i, i + 1, i + len(xs) + 1), (i, i + len(xs) + 1, i + len(xs))])
    write_obj(name, points, faces, description)


def scene(name, files, labels, metric, width, height, minimum=None, maximum=None, topology=False):
    # Two comparison objects show the A/B heatmaps together, with shared inputs.
    pair = len(files) == 2
    spacing = width + 2
    total_width = width + (spacing if pair else 0)
    text = "# Generated by generate.py; all mesh paths are relative.\nversion = 6\n"
    text += 'show_grid = false\nshow_origin = false\nup_axis = "z"\n'
    text += f"\n[camera]\ntarget = [{total_width / 2}, {height / 2}, 0]\n"
    text += f"yaw_radians = {math.pi / 2}\npitch_radians = {1.05 if topology else 1.4}\nroll_radians = 0\n"
    text += f"distance = {max(total_width, height) * 1.45}\nvertical_fov_degrees = 60\nnear_plane = 0.01\n"
    for filename in files:
        text += f'\n[[files]]\npath = "{filename}"\nvisible = false\n'
        text += '[[files.groups]]\nname = "surface"\nshow_vertices = false\nshow_triangles = false\n'
    for side, label in enumerate(labels):
        text += f'\n[[comparisons]]\nname = "{label}"\ntranslation = [{spacing * side}, 0, 0]\n'
        text += 'comparison_enabled = true\ncomparison_mode = "surface_quality"\n'
        text += 'comparison_show_edges = true\n'
        text += f"comparison_show_boundaries = {str(topology).lower()}\ncomparison_show_non_manifold = {str(topology).lower()}\n"
        text += f'quality_metric = "{metric}"\nquality_on_a = {str(side == 0).lower()}\n'
        text += f"quality_minimum_enabled = {str(minimum is not None).lower()}\nquality_minimum_size = {minimum or 0}\n"
        text += f"quality_maximum_enabled = {str(maximum is not None).lower()}\nquality_maximum_size = {maximum if maximum is not None else 1}\n"
        for i, filename in enumerate(files):
            text += f'[[comparisons.{"a" if i == 0 else "b"}]]\nfile_index = {i}\ngroup_index = 0\nname = "{filename} / surface"\n'
    (ROOT / name).write_text(text, encoding="utf-8", newline="\n")


def main():
    grid("coarse.obj", [0, 2, 4, 6], [0, 2, 4, 6], "18 right triangles; longest edge 2*sqrt(2).")
    grid("fine.obj", list(range(7)), list(range(7)), "72 right triangles; longest edge sqrt(2).")
    scene("01-coarse-vs-fine.woby", ["coarse.obj", "fine.obj"],
          ["A - Coarse: above 1.5 mm", "B - Fine: below 1.5 mm"], "longest_edge", 6, 6, maximum=1.5)

    for filename, bases in [("equilateral.obj", [2, 2, 2, 2]), ("equal-area-thin.obj", [2, 4, 8, 16])]:
        points, faces = [], []
        for row, base in enumerate(bases):
            i = len(points)
            points += [(8 - base / 2, row * 4, 0), (8 + base / 2, row * 4, 0),
                       (8, row * 4 + 2 * math.sqrt(3) / base, 0)]
            faces.append((i, i + 1, i + 2))
        write_obj(filename, points, faces, "Four isolated triangles, each area sqrt(3); equivalent size 2.")
    scene("02-equal-area-different-shapes.woby", ["equilateral.obj", "equal-area-thin.obj"],
          ["A - Equilateral: shape 1", "B - Equal area: progressively thinner"], "shape", 16, 14)

    grid("gradual.obj", list(range(5)), [0, .25, .75, 1.75, 3.75, 7.75],
         "40 triangles; successive strip heights .25, .5, 1, 2, 4. Maximum size jump sqrt(2).")
    grid("abrupt.obj", list(range(5)), [0, .25, 7.75],
         "16 triangles; strip heights .25 and 7.5. Maximum size jump sqrt(30).")
    scene("03-gradual-vs-abrupt.woby", ["gradual.obj", "abrupt.obj"],
          ["A - Gradual: max jump sqrt(2)", "B - Abrupt: max jump sqrt(30)"], "size_jump", 4, 7.75)

    write_obj("size-limits.obj", [(0, 0, 0), (3, 0, 0), (0, 4, 0), (5, 0, 0), (11, 0, 0), (5, 8, 0)],
              [(0, 1, 2), (3, 4, 5)], "3-4-5 and 6-8-10 triangles. Areas 6 and 24; longest edges 5 and 10.")
    scene("04-size-limits-and-area.woby", ["size-limits.obj"],
          ["One face outside limits: 50% of faces, 80% of area"], "longest_edge", 11, 8, minimum=5, maximum=5)

    points, faces = [], []

    def component(vertices, triangles):
        offset = len(points)
        points.extend(vertices)
        faces.extend(tuple(offset + i for i in t) for t in triangles)

    component([(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0)], [(0, 1, 2), (0, 2, 3)])
    component([(3, 0, 0), (4, 0, 0), (3, 1, 0)], [(0, 1, 2)])
    component([(6, 0, 0), (7, 0, 0), (6.5, 1, 0), (6.5, -1, 0), (6.5, 0, 1)],
              [(0, 1, 2), (1, 0, 3), (0, 1, 4)])
    component([(0, 4, 0), (1, 4, 0), (1, 5, 0), (0, 5, 0)], [(0, 1, 2), (0, 3, 2)])
    component([(3, 4, 0), (4, 4, 0), (3, 5, 0)], [(0, 1, 2), (2, 1, 0)])
    component([(6, 4, 0), (7, 4, 0), (8, 4, 0)], [(0, 1, 2), (0, 0, 1)])
    write_obj("topology.obj", points, faces,
              "Regular patch, isolated triangle, non-manifold fan, winding patch, duplicate, and two degenerate faces.")
    scene("05-topology-and-unavailable.woby", ["topology.obj"],
          ["Topology: 2 degenerate, 1 duplicate, 4 unavailable ratios"], "size_jump", 8, 6, topology=True)

    # Partial expectations intentionally emphasize independent analytical checks.
    root3 = math.sqrt(3)
    expected = {
        "01-coarse-vs-fine.woby": {
            "a": {"triangleCount": 18, "longest_edge.minimum": 2 * math.sqrt(2), "longest_edge.maximum": 2 * math.sqrt(2),
                  "equivalent_size.median": 2 * math.sqrt(2 / root3), "shape.minimum": root3 / 2, "size_jump.maximum": 1,
                  "limits.above": 18, "limits.trianglePercent": 100, "limits.areaPercent": 100},
            "b": {"triangleCount": 72, "longest_edge.minimum": math.sqrt(2), "longest_edge.maximum": math.sqrt(2),
                  "shape.minimum": root3 / 2, "size_jump.maximum": 1, "limits.above": 0, "limits.areaPercent": 0}},
        "02-equal-area-different-shapes.woby": {
            "a": {"triangleCount": 4, "equivalent_size.minimum": 2, "equivalent_size.maximum": 2,
                  "shape.minimum": 1, "shape.maximum": 1, "size_jump.count": 0, "size_jump.maximum": None},
            "b": {"triangleCount": 4, "equivalent_size.minimum": 2, "equivalent_size.maximum": 2,
                  "shape.minimum": 128 / 4097, "shape.maximum": 1, "longest_edge.maximum": 16, "size_jump.count": 0}},
        "03-gradual-vs-abrupt.woby": {
            "a": {"triangleCount": 40, "size_jump.maximum": math.sqrt(2), "size_jump.minimum": 1},
            "b": {"triangleCount": 16, "size_jump.maximum": math.sqrt(30), "size_jump.minimum": 1}},
        "04-size-limits-and-area.woby": {
            "a": {"triangleCount": 2, "longest_edge.minimum": 5, "longest_edge.maximum": 10, "longest_edge.median": 7.5,
                  "longest_edge.percentile5": 5.25, "longest_edge.percentile95": 9.75,
                  "limits.below": 0, "limits.above": 1, "limits.trianglePercent": 50, "limits.areaPercent": 80}},
        "05-topology-and-unavailable.woby": {
            "a": {"triangleCount": 12, "shape.count": 10, "size_jump.count": 6, "size_jump.maximum": 1,
                  "diagnostics.degenerateTriangles": 2, "diagnostics.duplicateTriangles": 1,
                  "diagnostics.boundaryEdges": 17, "diagnostics.nonManifoldEdges": 1,
                  "diagnostics.inconsistentWindingEdges": 1}}
    }
    (ROOT / "expected.json").write_text(json.dumps(expected, indent=2) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
