include_guard(GLOBAL)

function(woby_discover_tests target)
    set(discovery_directory "${CMAKE_CURRENT_BINARY_DIR}/test-discovery/${target}")
    get_target_property(test_executor ${target} CROSSCOMPILING_EMULATOR)
    if(NOT test_executor)
        set(test_executor "")
    endif()
    file(GENERATE OUTPUT "${discovery_directory}/$<CONFIG>/include.cmake" CONTENT
"set(TEST_TARGET [==[${target}]==])
set(TEST_EXECUTABLE [==[$<TARGET_FILE:${target}>]==])
set(TEST_EXECUTOR [==[${test_executor}]==])
set(TEST_WORKING_DIR [==[${CMAKE_CURRENT_BINARY_DIR}]==])
set(CTEST_FILE [==[${discovery_directory}/$<CONFIG>/tests.cmake]==])
set(DOCTEST_SCRIPT [==[${_DOCTEST_DISCOVER_TESTS_SCRIPT}]==])
set(DISCOVERY_CONFIG \"\${CMAKE_CURRENT_LIST_FILE}\")
if(EXISTS \"\${TEST_EXECUTABLE}\")
    include([==[${CMAKE_CURRENT_FUNCTION_LIST_DIR}/DiscoverTestsIfNeeded.cmake]==])
    include(\"\${CTEST_FILE}\")
else()
    add_test(${target}_NOT_BUILT ${target}_NOT_BUILT)
endif()
")
    if(CMAKE_CONFIGURATION_TYPES)
        set(configuration "\${CTEST_CONFIGURATION_TYPE}")
    else()
        set(configuration "${CMAKE_BUILD_TYPE}")
    endif()
    file(GENERATE OUTPUT "${discovery_directory}/include.cmake" CONTENT
"if(NOT EXISTS \"${discovery_directory}/${configuration}/include.cmake\")
    message(FATAL_ERROR \"Select a built configuration with ctest -C <configuration>\")
endif()
include(\"${discovery_directory}/${configuration}/include.cmake\")
")
    set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES
        "${discovery_directory}/include.cmake")
endfunction()
