include_guard(GLOBAL)

function(woby_enable_project_warnings target)
    if(MSVC)
        target_compile_options("${target}" PRIVATE /W4 /permissive- /EHs)
    else()
        target_compile_options("${target}" PRIVATE -Wall -Wextra -Wpedantic)
    endif()
endfunction()

function(woby_enable_enum_switch_warnings target)
    if(MSVC)
        target_compile_options("${target}" PRIVATE /we4061 /we4062)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "^(AppleClang|Clang|GNU)$")
        target_compile_options("${target}" PRIVATE -Wswitch-enum -Werror=switch-enum)
    endif()
endfunction()
